colo molokai_modified7
syntax on
set tabstop=4              
set expandtab
set softtabstop=4             
set autoindent           
set smartindent
set formatoptions+=r
set nu                
set bg=dark
